Add lexicographic comparison task for 2 strings
FedorovAlexander/Front-end-Job-Interview-Questions pull request #61
Opened 2024-09-11 14:33 UTC by vvaxcoder

Добавил задачу с решением для секции Coding
Написать функцию, которая принимает 2 строки и возвращает результат их лексикографического сравнения.

2024-09-12 18:51 UTC, FedorovAlexander requested changes
Спасибо, что добавил новый вопрос.
Посмотри плз комменты. Есть небольшие замечания по коду и опечатки в тексте.

2024-09-12 18:51 UTC, FedorovAlexander commented on Coding/README.md
> +  }
Можно не использовать `if/else` и вернуть сразу `return l1.join('') === l2.join('');`

2024-09-12 18:51 UTC, FedorovAlexander commented on Coding/README.md
> +  if (l1.join() === l2.join()) {
Используй .join('') вместо .join(), чтобы строки сравнивались корректно (без добавления запятых).
![Screenshot 2024-09-12 214213](https://github.com/user-attachments/assets/39507729-ae53-4d64-b8da-d0b0d2ee3148)

2024-09-12 18:51 UTC, FedorovAlexander commented on Coding/README.md
> +Ответ: для решения задачи нужно разбить дву строки посимвольно, используя метод split, и, полученный массивы отсортировать по возрастанию с использованием стандартного метода sort. Псоле чего к получ
```suggestion
Ответ: для решения задачи нужно разбить две строки посимвольно, используя метод split, и полученные массивы отсортировать по возрастанию с использованием стандартного метода sort. После этого к отсортированным массивам применить метод join, который создаст из них строки, и сравнить эти строки. Результат сравнения вернуть из функции.
```

2024-09-13 07:01 UTC, vvaxcoder commented on Coding/README.md
> +  }
Поправил

2024-09-13 07:01 UTC, vvaxcoder commented on Coding/README.md
> +  if (l1.join() === l2.join()) {
Этот момент тоже поправил

2024-09-13 07:02 UTC, vvaxcoder commented on Coding/README.md
> +Ответ: для решения задачи нужно разбить дву строки посимвольно, используя метод split, и, полученный массивы отсортировать по возрастанию с использованием стандартного метода sort. Псоле чего к получ
В тексте убрал лишние помарки и орфографические ошибки

2024-09-13 07:58 UTC, FedorovAlexander approved these changes

2024-09-13 07:58 UTC, merged